export const projects = [
  {
    title: "Umba",
    description:
      "This is a React project that clones the Umba website. It is a fully functional website having a responsive layout.",
    image: "",
    tags: ["Html", "CSS", "React"],
    source: "https://github.com/wisdom-egba/Umba-clone",
    visit: "https://umba-clone.vercel.app/",
    id: 0,
  },
  {
    title: "Rock paper scissor",
    description: "",
    image: "",
    tags: ["Html", "CSS", "Javascript"],
    source: "",
    visit: "",
    id: 1,
  },
  {
    title: "Buildz-Landing Page",
    description: "",
    image: "",
    tags: ["Html", "CSS", "React JS", "Framer Motion"],
    source: "https://github.com/wisdom-egba/Buildz-Landing-Page",
    visit: "https://buildz-landing-page.vercel.app/",
    id: 2,
  },
  {
    title: "Landing Page",
    description: "",
    image: "",
    tags: [],
    source: "",
    visit: "",
    id: 3,
  },
  {
    title: "Expense Tracker",
    description: "The Expense tracker app helps track your daily purchase",
    image: "",
    tags: ["Html", "CSS", "Next JS"],
    source: "",
    visit: "",
    id: 4,
  },
]
